name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        docker run --rm -v $(pwd):/home/ -i rhrhunter/vcv-build-env:ubuntu18.04-rack1.1.6 make -C /home/
        docker run --rm -v $(pwd):/home/ -i rhrhunter/vcv-build-env:ubuntu18.04-rack1.1.6 gcc -x c++ /home/src/FV1emu.hpp -o /home/test -DTEST -lstdc++
    - name: Test
      run: |
        chmod u+x ./test
        ./test ./fx/demo.spn
